config/routes.rb
Rails.application.routes.draw do
  root 'friend_num#home'
  post '/result' => 'friend_num#result', as: 'friend_num'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friend_num_controller.rb
class FriendNumController < ApplicationController
  attr_accessor :res, :num

  def home; end
  
  def sum_divisors(arg)
    sum = 0
    (1...arg).each do |div|
      sum += div if arg % div == 0
    end
    sum
  end

  def check
    arr = Array.new(0)
    sum = Array.new(num)
    (1..num).each {|index| sum[index] = sum_divisors(index)}
    (1..num - 1).each do |num1|
      (num1..num).each do |num2|
        arr.append([num1, num2]) if num1 != num2 && num1 == sum[num2] && sum[num1] == num2
      end
    end
    arr
  end

  def result
    @num = params[:num].to_i
    @res = check
    respond_to do |format|
      format.html { redirect_to :root }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_num_helper.rb
module FriendNumHelper
end

app/views/friend_num/_result.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Result</title>
</head>
<body>
    <h1>RESULT TABLE - Friend numbers</h1>
    <table class="table table-bordered">
        <tr>
            <th>The first number</th>
            <th>The second number</th>
        </tr>
        <% @res.each do |couple| %>
        <tr>
            <td><%= couple[0] %> </td>
            <td><%= couple[1] %> </td>
        </tr>
        <% end %>
    </table>
</body>
</html>

app/views/friend_num/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title><%= @title %></title>
</head>
<body>
    <h1><%= @title %></h1>
    <p>Two numbers are called friend if each of them is equal to the sum of all divisors of another, except for this number itself. </p>
    <%= form_with(url: friend_num_path, method: "post", local: false) do |form|%>
        <%= form.label :num, "Enter n: " %>
        <%= form.text_field :num %>
        <div class="button">
            <%= form.submit "Get result" %>
        </div>
    <% end %> 
    <div id="result"></div>
    <script>
        const resultDiv = document.querySelector("#result");
    </script>
</body>
</html>

app/views/friend_num/result.js.erb
resultDiv.innerHTML = '<%= escape_javascript(render(partial: 'friend_num/result')) %>';
console.log("RENDERED");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>